matrix:
  include:
    - os: linux
      sudo: required
      dist: bionic
      compiler: gcc
    - os: osx

language: cpp

before_install:
  - MY_LOCATION=`pwd`
  - mkdir ../repositories
  - cd ..
  - mv $MY_LOCATION repositories
  - QUICKY_REPOSITORY=`pwd`/repositories
  - export QUICKY_REPOSITORY
  - MY_LOCATION=`pwd`
  - cd $MY_LOCATION/repositories
  - git clone https://github.com/quicky2000/quicky_tools.git
  - git clone https://github.com/quicky2000/lib_gif.git
  - git clone https://github.com/quicky2000/lib_bmp.git
  - git clone https://github.com/quicky2000/parameter_manager.git
  - git clone https://github.com/quicky2000/quicky_exception.git
  - git clone https://github.com/quicky2000/quicky_utils.git
  - cd quicky_tools/setup
  - . setup.sh
  - cd $MY_LOCATION
  - chmod a+x repositories/quicky_tools/bin/*

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir build; cd build; generate_makefile gif_streamer ; make test; fi
  - cd $MY_LOCATION ; mkdir cmake_build ; cd cmake_build ; cmake $QUICKY_REPOSITORY/gif_streamer
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd $MY_LOCATION/build ; ./bin/gif_streamer.exe  --delay-ms=500 --nb-files=14 "$QUICKY_REPOSITORY/gif_streamer/test/example_#.bmp" && diff stream.gif $QUICKY_REPOSITORY/gif_streamer/test/ref.gif ; fi
  - cd $MY_LOCATION/cmake_build
  - ./gif_streamer  --delay-ms=500 --nb-files=14 "$QUICKY_REPOSITORY/gif_streamer/test/example_#.bmp" && diff stream.gif $QUICKY_REPOSITORY/gif_streamer/test/ref.gif
#EOF
